# Run with:
#   docker-compose up

version: '3.4'
services:
    # We do not need a database, for now,
    # since we are but a client for the OpenAPI.
    # We might need one later, but perhaps a redis will suffice.
    #mysql:
        #image: mysql:8.0
        #restart: on-failure
        #environment:
        #MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        #MYSQL_DATABASE: ${MYSQL_DATABASE}

    php:
        container_name: cli_mieuxvoter_fr_php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: on-failure
        volumes:
          - './docker/public:/usr/src/app/public'
        #user: ${LOCAL_USER}

    nginx:
        container_name: cli_mieuxvoter_fr_nginx
        image: nginx:1.19.0-alpine
        restart: on-failure
        ports:
            - "9001:80"
        volumes:
            - './docker/public:/public:ro'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        depends_on:
            - php
