# Run with:
#   docker-compose up

# docker-compose on MV server is a bit behind
# 3.9 does not work there (for now)
version: '3.4'

volumes:
  public_assets:
    name: public_assets
    external: true
  goaccess_report:
    name: goaccess_report

services:
    # We do not need a database, for now,
    # since we are but a client for the OpenAPI.
    # We might need one later, but perhaps a redis will suffice.
    #mysql:
        #image: mysql:8.0
        #restart: on-failure
        #environment:
        #MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        #MYSQL_DATABASE: ${MYSQL_DATABASE}

    php:
        container_name: cli_mieuxvoter_fr_php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: on-failure
        volumes:
            - public_assets:/usr/src/app/public
        environment:
            BANANA: teapot
            # Set to "dev" to enable the debug goodies
            #APP_ENV: dev
            # Don't use this, since docker-compose loads .env and ignores .env.local
            # This has happened to me too many times >.<
            #APP_ENV: ${APP_ENV:-prod}
        #user: ${LOCAL_USER}

    nginx:
        container_name: cli_mieuxvoter_fr_nginx
        image: nginx:1.19.0-alpine
        restart: on-failure
        ports:
            - "9001:80"
        volumes:
            # In newer docker-compose, there's a `config` shortcut for this I believe
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            # We could also use a named volume here, no reason except debugging it isn't
            - ./volumes/log_nginx:/var/log/nginx
            # Project static assets built by the cli_mieuxvoter_fr_php container
            - public_assets:/public:ro
            # GoAccess HTML report and debug log
            - goaccess_report:/goaccess:ro
            # Nope ; we need to cook our own .htpasswd from ENV
            - ./docker/nginx/.htpasswd:/nginx/.htpasswd:ro
        depends_on:
            - php

    # One-shot container, for now.
    # Generates HTML report and exits.
    #   docker-compose up goaccess
    # Or run `bin/goaccess` in a CRON task every hour or so?
    goaccess:
        container_name: cli_mieuxvoter_fr_goaccess
        # latest=1.5.7 ATM
        #image: allinurl/goaccess:latest
        # We use our own Dockerfile, mostly to get `zcat`.
        build:
          context: .
          dockerfile: docker/goaccess/Dockerfile
        volumes:
            - ./volumes/log_nginx:/var/log/nginx:ro
            - ./docker/goaccess:/goaccess:ro
            - goaccess_report:/srv/report
        entrypoint: /bin/sh /goaccess/goaccess_entrypoint.sh
        command:
            - "--config-file=/goaccess/goaccess.conf"
            - "--no-global-config"
            - "--debug-file=/srv/report/debug.log"
            - "--output=/srv/report/index.html"
            # Expensive.   We only want to generate from time to time.  See CRON.
#            - "--real-time-html"
            # We read from stdin and zcat now to get logrotated files, see the entrypoint
#            - "--log-file=/var/log/nginx/access.log"
#            - "--log-file=/var/log/nginx/error.log"
#        ports:
#            - published: 7890
#              target: 7890
#              protocol: tcp
#              mode: host
#        expose:
#            - 7890