# Run with:
#   docker-compose up

version: '3.4'

volumes:
  public_assets:
    name: public_assets
    external: true
  goaccess_report:
    name: goaccess_report

services:
    # We do not need a database, for now,
    # since we are but a client for the OpenAPI.
    # We might need one later, but perhaps a redis will suffice.
    #mysql:
        #image: mysql:8.0
        #restart: on-failure
        #environment:
        #MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        #MYSQL_DATABASE: ${MYSQL_DATABASE}

    php:
        container_name: cli_mieuxvoter_fr_php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: on-failure
        volumes:
            - public_assets:/usr/src/app/public
        environment:
            BANANA: teapot
            # Set to "dev" to enable the debug goodies
            #APP_ENV: dev
            # Don't use this, since docker-compose loads .env and ignores .env.local
            # This has happened to me too many times >.<
            #APP_ENV: ${APP_ENV:-prod}
        #user: ${LOCAL_USER}

    nginx:
        container_name: cli_mieuxvoter_fr_nginx
        image: nginx:1.19.0-alpine
        restart: on-failure
        ports:
            - "9001:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./docker/nginx/.htpasswd:/nginx/.htpasswd:ro
            - ./volumes/log_nginx:/var/log/nginx
            - public_assets:/public:ro
            - goaccess_report:/goaccess:ro
        depends_on:
            - php

    # One-shot container, for now.
    # Generates HTML report and exits.
    #   docker-compose up goaccess
    goaccess:
        container_name: cli_mieuxvoter_fr_goaccess
        image: allinurl/goaccess:latest
        # latest=1.5.7 ATM
        volumes:
            # Mmmmh ; not fond of this ; it's for the docker logs call below
            # It is a trick to allow real-time updating.
#            - /var/run/docker.sock:/var/run/docker.sock
            ################################################################
            - ./volumes/log_nginx:/var/log/nginx:ro
            - ./docker/goaccess:/goaccess:ro
            - goaccess_report:/srv/report
        entrypoint: /bin/sh /goaccess/goaccess_entrypoint.sh
        command:
            - "--config-file=/goaccess/goaccess.conf"
            - "--no-global-config"
#            - "--real-time-html"
            - "--log-file=/var/log/nginx/access.log"
            - "--log-file=/var/log/nginx/error.log"
            - "--debug-file=/srv/report/debug.log"
            - "--output=/srv/report/index.html"
#        command: sh -c "apk add --update --no-cache docker && docker service logs -f --raw cli_mieuxvoter_fr_nginx 2>&1| goaccess --config-file=/goaccess/goaccess.conf --no-global-config --real-time-html --log-format=COMBINED -"
#        ports:
#            - published: 7890
#              target: 7890
#              protocol: tcp
#              mode: host
#        expose:
#            - 7890